from .other import register_handlers_other
from .added_student import register_handlers_student_added
from .del_student import register_handlers_student_del
from .added_group import register_handlers_groups_added
from .del_group import register_handlers_group_del
from .output_studets import register_handlers_output_students
from .go import register_handlers_go
from .get_data import register_handlers_excel
